# Generated by Django 3.0 on 2025-10-30 04:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Food_Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Name', models.CharField(max_length=50)),
                ('Photo', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Dob', models.DateField()),
                ('Email', models.CharField(max_length=100)),
                ('Gender', models.CharField(max_length=30)),
                ('Phone', models.CharField(max_length=30)),
                ('Photo', models.CharField(max_length=500)),
                ('Place', models.CharField(max_length=100)),
                ('Post', models.CharField(max_length=100)),
                ('District', models.CharField(max_length=100)),
                ('State', models.CharField(max_length=100)),
                ('Pin', models.CharField(max_length=100)),
                ('AUTH_USER', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Health_Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Height', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('Bmi', models.CharField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=50)),
                ('Is_Cardiac', models.CharField(max_length=50)),
                ('Body_Type', models.CharField(max_length=50)),
                ('Bp', models.CharField(max_length=50)),
                ('Cholestrol', models.CharField(max_length=50)),
                ('Sugar_level', models.CharField(max_length=50)),
                ('Thyroid_Status', models.CharField(max_length=50)),
                ('Waist_Circumference', models.CharField(max_length=50)),
                ('Hip_Circumference', models.CharField(max_length=50)),
                ('Bone_Density_Tscore', models.CharField(max_length=50)),
                ('Vitamin_D_Level', models.CharField(max_length=50)),
                ('Iron_Ferritin', models.CharField(max_length=50)),
                ('Smoking', models.CharField(max_length=50)),
                ('Alcohol_Consumption', models.CharField(max_length=50)),
                ('Physical_Activity_Level', models.CharField(max_length=50)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Feedback', models.CharField(max_length=300)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Daily_Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_Time', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Type', models.CharField(max_length=100)),
                ('FOOD_DATABASE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Food_Database')),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField()),
                ('Complaint', models.CharField(max_length=300)),
                ('Status', models.CharField(max_length=50)),
                ('Reply', models.CharField(max_length=50)),
                ('USERS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Users')),
            ],
        ),
    ]
