# Generated by Django 3.0 on 2026-02-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='daily_food',
            name='Carbohydrate',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daily_food',
            name='Fat',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='daily_food',
            name='Protein',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
