# Generated by Django 3.0 on 2026-02-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20260215_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_profile',
            name='healthprofile',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
