# Generated by Django 3.0 on 2026-02-23 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_health_profile_healthprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='health_profile',
            name='carbvalue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_profile',
            name='fatvalue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='health_profile',
            name='protienvalue',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
